WITH ITEM_ROOT AS (
    SELECT
        *
    FROM ITEM_TREE
    WHERE
        PARENT_ITEM_ID IS NULL
)
SELECT
    II.ITEM_ID,
    II.ITEM_NAME
FROM ITEM_ROOT AS IR
INNER JOIN ITEM_INFO AS II
ON IR.ITEM_ID = II.ITEM_ID
ORDER BY
    II.ITEM_ID