SELECT
    ED1.id
FROM ECOLI_DATA AS ED1
LEFT JOIN ECOLI_DATA AS ED2
ON ED1.PARENT_ID = ED2.ID
LEFT JOIN ECOLI_DATA AS ED3
ON ED2.PARENT_ID = ED3.ID
WHERE
    1=1
    AND ED3.parent_id IS NULL
    AND ED3.id IS NOT NULL
ORDER BY
    ED1.id