#더이상 업그레이드 할 수 없는 아이템의 아이템 ID,NAME,RARITY를 출력

SELECT
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM ITEM_TREE AS IT
LEFT JOIN ITEM_TREE AS IT1
ON IT.ITEM_ID = IT1.PARENT_ITEM_ID
INNER JOIN ITEM_INFO AS II
ON IT.ITEM_ID = II.ITEM_ID
WHERE
    1=1
    AND IT1.PARENT_ITEM_ID IS NULL
ORDER BY
    II.ITEM_ID DESC