# SELECT
#     COUNT(*) AS USERS
# FROM USER_INFO
# WHERE
#     1=1
#     AND age BETWEEN 20 AND 29
#     AND EXTRACT(YEAR FROM JOINED) = 2021

SELECT
    COUNT(*)
FROM USER_INFO
WHERE
    1=1
    AND EXTRACT(YEAR FROM JOINED) = 2021
    AND AGE BETWEEN 20 AND 29