SELECT
    ID,
    CASE 
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) % 4 = 1 THEN 'CRITICAL'
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) % 4 = 2 THEN 'HIGH'
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) % 4 = 3 THEN 'MEDIUM'
        WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) % 4 = 0 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY
    ID