SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
INNER JOIN REST_REVIEW AS RR
ON RI.REST_ID = RR.REST_ID
WHERE
    1=1
    AND SUBSTR(RI.ADDRESS,1,2) = '서울'
GROUP BY
    2
ORDER BY
    SCORE DESC,
    RI.FAVORITES DESC
    
# SELECT
#     R1.REST_ID,
#     R1.REST_NAME,
#     R1.FOOD_TYPE,
#     R1.FAVORITES,
#     R1.ADDRESS,
#     R2.SCORE
# FROM REST_INFO AS R1
# INNER JOIN (SELECT
#                 REST_ID,
#                 ROUND(AVG(REVIEW_SCORE),2) AS SCORE
#             FROM REST_REVIEW
#             GROUP BY
#                 REST_ID) AS R2
# ON R1.REST_ID = R2.REST_ID
# WHERE
#     1=1
#     AND SUBSTR(R1.ADDRESS,1,2) = '서울'
# ORDER BY
#     R2.SCORE DESC,
#     R1.FAVORITES DESC