WITH REVIEW_AVG AS (
SELECT
    REST_ID,
    ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW
GROUP BY
    REST_ID
)
SELECT
    RI.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    SCORE
FROM REST_INFO AS RI
INNER JOIN REVIEW_AVG AS RA
ON RI.REST_ID = RA.REST_ID
WHERE
    1=1
    AND ADDRESS LIKE '서울%'
ORDER BY
    SCORE DESC,
    FAVORITES DESC