# 쿼리를 작성하는 목표, 확인할 지표 : CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명 : FEE) 을 구하여    대여 기록 ID와 대여 금액 리스트를 출력하는 쿼리 작성
# 쿼리 계산 방법 : CAR_RENTAL_COMPANY_CAR와 CAR_RENTAL_COMPANY_RENTAL_HISTORY를 JOIN하여 트럭의 기록을 가져와서 DATE를 뺄샘하여 몇일 빌렸는지 알아낸후 CAR_RENTAL_COMPANY_DISCOUNT_PLAN이 테이블에 날짜를 숫자로 정정하여 적는다. JOIN할 수 있도록 컬럼을 만들어준다. 할인율을 적용한다
# 쿼리 결과 : HISTORY_ID | FEE
# 데이터의 기간 : x
# 사용할 테이블 : CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY, CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# Join KEY : 
# 데이터 특징 : x

WITH CAR_TYPE_TRUCK AS (
    SELECT
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE
        1=1
        AND CAR_TYPE = '트럭'
), CAR_TYPE_TRUCK_HISTORY AS (
    SELECT
        C1.CAR_ID,
        C1.CAR_TYPE,
        C1.DAILY_FEE,
        C2.HISTORY_ID,
        C2.START_DATE,
        C2.END_DATE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DATE
    FROM CAR_TYPE_TRUCK AS C1
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C2
    ON C1.CAR_ID = C2.CAR_ID
)
SELECT
    HISTORY_ID,
    CASE
        WHEN C2.PLAN_ID IS NOT NULL THEN ROUND((DAILY_FEE - (DAILY_FEE * 0.01 * DISCOUNT_RATE)) * DATE,0)
    ELSE DAILY_FEE * DATE
    END AS FEE
FROM CAR_TYPE_TRUCK_HISTORY AS C1
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C2
ON C1.CAR_TYPE = C2.CAR_TYPE
AND ((C2.DURATION_TYPE = '7일 이상' AND C1.DATE >= 7 AND C1.DATE < 30)
OR (C2.DURATION_TYPE = '30일 이상' AND C1.DATE >= 30 AND C1.DATE < 90)
OR (C2.DURATION_TYPE = '90일 이상' AND C1.DATE >= 90))
ORDER BY
    FEE DESC,
    HISTORY_ID DESC