WITH SP AS (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS SUM_PRICE
    FROM USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM_PRICE >= 700000
)

SELECT
    S.WRITER_ID,
    NICKNAME,
    SUM_PRICE
FROM USED_GOODS_USER AS UGU
INNER JOIN SP AS S
ON UGU.USER_ID = S.WRITER_ID
ORDER BY
    SUM_PRICE