# SELECT
#     HOUR(DATETIME) AS HOUR,
#     COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# WHERE
#     HOUR(DATETIME) BETWEEN 9 AND 19
# GROUP BY
#     HOUR
# ORDER BY
#     HOUR

SELECT
    EXTRACT(HOUR FROM DATETIME) AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE
    1=1
    AND HOUR(DATETIME) >= 9
    AND HOUR(DATETIME) < 20
GROUP BY
    1
ORDER BY
    HOUR