# SELECT
#     II.FLAVOR
# FROM ICECREAM_INFO AS II
# INNER JOIN FIRST_HALF AS FH
# ON II.FLAVOR = FH.FLAVOR
# WHERE
#     1=1
#     AND INGREDIENT_TYPE = 'fruit_based'
#     AND TOTAL_ORDER > 3000
# ORDER BY
#     TOTAL_ORDER DESC

WITH ORDER3000 AS (
    SELECT
        *
    FROM FIRST_HALF
    WHERE
        1=1
        AND TOTAL_ORDER > 3000
)
SELECT
    O3.FLAVOR
FROM ICECREAM_INFO AS II
INNER JOIN ORDER3000 AS O3
ON II.FLAVOR = O3.FLAVOR
WHERE
    1=1
    AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    O3.TOTAL_ORDER DESC


