SELECT
    FH.FLAVOR
FROM FIRST_HALF AS FH
LEFT JOIN ICECREAM_INFO AS II
ON FH.FLAVOR = II.FLAVOR
WHERE
    1=1
    AND TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    TOTAL_ORDER DESC


/*WITH order3000 AS (
SELECT
    *
FROM FIRST_HALF
WHERE
    TOTAL_ORDER > 3000
)
SELECT
    II.FLAVOR
FROM order3000 AS o3
LEFT JOIN ICECREAM_INFO AS II
ON o3.FLAVOR = II.FLAVOR
WHERE
    INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    TOTAL_ORDER DESC*/