WITH order3000 AS (
SELECT
    *
FROM FIRST_HALF
WHERE
    TOTAL_ORDER > 3000
)
SELECT
    II.FLAVOR
FROM order3000 AS o3
LEFT JOIN ICECREAM_INFO AS II
ON o3.FLAVOR = II.FLAVOR
WHERE
    INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    TOTAL_ORDER DESC