# SELECT
#     BOOK_ID,
#     DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
# FROM BOOK
# WHERE
#     1=1
#     AND EXTRACT(YEAR FROM PUBLISHED_DATE) = 2021
#     AND category = '인문'
# ORDER BY
#     PUBLISHED_DATE

# SELECT
#     BOOK_ID,
#     DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')
# FROM BOOK
# WHERE
#     1=1
#     AND EXTRACT(YEAR FROM PUBLISHED_DATE) = 2021
#     AND CATEGORY = '인문'
# ORDER BY
#     PUBLISHED_DATE

SELECT
    book_id,
    DATE_FORMAT(published_date,'%Y-%m-%d') AS published_date
FROM BOOK
WHERE
    1=1
    AND CATEGORY = '인문'
    AND YEAR(PUBLISHED_DATE) = 2021












