WITH MAX_SCORE AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY
        EMP_NO
    ORDER BY
        SCORE DESC
    LIMIT
        1
)
SELECT
    SCORE,
    MS.EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM MAX_SCORE AS MS
INNER JOIN HR_EMPLOYEES AS HE
ON MS.EMP_NO = HE.EMP_NO