SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB
INNER JOIN USED_GOODS_REPLY AS UGR
ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE
    1=1
    # AND UGB.CREATED_DATE >= STR_TO_DATE('2022-10-01', '%Y-%m-%d')
    # AND UGB.CREATED_DATE < STR_TO_DATE('2022-11-01', '%Y-%m-%d')
    AND DATE_FORMAT(UGB.CREATED_DATE,'%Y-%m') LIKE '2022-10%'

ORDER BY
    UGR.CREATED_DATE,
    UGB.TITLE