WITH DATE202210 AS (
    SELECT
        TITLE,
        BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE
        SUBSTRING(CREATED_DATE,1,7) = '2022-10'
)
SELECT
    TITLE,
    D2210.BOARD_ID,
    REPLY_ID,
    WRITER_ID,
    CONTENTS,
    DATE_FORMAT(CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM DATE202210 AS D2210
INNER JOIN USED_GOODS_REPLY AS UGR
ON D2210.BOARD_ID = UGR.BOARD_ID
ORDER BY
    CREATED_DATE,
    TITLE