WITH AVG_S AS (
    SELECT
        DEPT_ID,
        ROUND(AVG(SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY
        DEPT_ID
)
SELECT
    A.DEPT_ID,
    DEPT_NAME_EN,
    A.AVG_SAL
FROM AVG_S AS A
INNER JOIN HR_DEPARTMENT AS HD
ON A.DEPT_ID = HD.DEPT_ID
ORDER BY
    AVG_SAL DESC
