WITH CTE AS (
    SELECT
        FISH_TYPE,
        AVG(IFNULL(LENGTH,10)) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY
        FISH_TYPE
    HAVING
        AVG(IFNULL(LENGTH,10)) > 33
)
SELECT
    COUNT(*)FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FI.FISH_TYPE
FROM FISH_INFO AS FI
INNER JOIN CTE AS C
ON FI.FISH_TYPE = C.FISH_TYPE
GROUP BY
    FI.FISH_TYPE
ORDER BY
    FI.FISH_TYPE